### PR TITLE
More consolefunctions

### PR DESCRIPTION
**Pull request by MusicMonkey5555**
Added a bunch of console functions that could be useful including in script type checking.

### CODE REVIEW

**Comment by dottools** [comment]
Changes have tabs vs 3 spaces indention issues. And your String class modifications weren't apart of the PR so it is failing to build:
```
Engine/source/console/consoleFunctions.cpp:836:17: fatal error: no member named 'GetFirstNumber' in 'String' return String::GetFirstNumber(str, start, end);
```

**Comment by MusicMonkey5555** [comment]
Yeah sorry missed that change. I added it to the branch before this comment even came up.
I will fix the spacing and resubmit it, we internally use tabs over space so I am afraid many improvements I would like to submit may run into this.

Is there any tool to go through and fix it before committing?

**Comment by MusicMonkey5555** [comment]
Ok so I added more console functions and all the spacing issues should be fixed. I also made sure it all compiled since many of my changes I split into a couple branches.

**Comment by eightyeight** [comment]
13 days ago? Why did I only notice this this morning? :c

**Comment by Lopuska** [comment]
Closing this as I fixed a little problem on that. The new PR -> #1532

**Pull request closed without merging**
