### PR TITLE
Allow using ThreadPool synchronously

### PR DESCRIPTION
**Pull request by eightyeight**
Previously, a test was using `ThreadPool::flushWorkItems` as if it would wait for all work items to complete before returning. This is incorrect - see #1174. Actually, `flushWorkItems` just waits until all items have _begun_, so if you have long-running items, they may be still happening.

This PR adds two things:

 1. A method `hasExecuted` on `WorkItem` to see if the item has finished executing.
 2. A method `waitForAllItems` on `ThreadPool` to block until no items are currently executing.

This lets you use the `ThreadPool` completely synchronously, as demonstrated by the new tests.

### CODE REVIEW

**Comment by rextimmy** [comment]
Ooh great work :) i had this problem when i was playing around with the thread pools and i ended up testing with intel tbb instead.

**Comment by eightyeight** [comment]
Huh, TBB does look cool.

**Comment by rextimmy** [comment]
Oh i meant i had the synchronizing problems when i was testing out a few things with T3D's ThreadPool. Yep TBB is a very nice library.

**Comment by Areloch** [comment]
I'll be honest. I'm not sure how to test this. Glancing at the changes, I see it adds the stuff, but I don't know how to kick off the testing of it?

**Comment by eightyeight** [comment]
You could run the unit tests ;). `torque.exe runTests.cs`

**Comment by JeffProgrammer** [comment]
I kind of makes sense on how flush originally worked as intended. at least in OpenGL, a flush command simply "flushes" the GL commands to the gpu, while swapBuffers actually is the blocking call. I kinda always assumed that a flush ment not blocking, rather just push everything out of the queue. However, I do like having the option for sync! :+1:

**Comment by eightyeight** [comment]
Thanks, that makes sense!

**Pull request merged**
