### PR TITLE
Bringing some parameters up to speed.

### PR DESCRIPTION
**Pull request by Winterleaf**
Update to the max number of ghosts, as well as to default connection speeds.

The connection speeds reflect the high speed nature the internet is now.

### CODE REVIEW

**Comment by Areloch** [comment]
I'll re-do this PR with the 508 for the packet size as suggested by @dottools 

@dottools do you think that 32 is good on the packet rate, or is leaving it at 10 ideal?

**Comment by eightyeight** [comment]
Sounds good.

**Comment by dottools** [comment]
@Areloch I think it's a safe bet to keep the `gPacketRateToClient` default at 10 Hz and let users/developers change that as they see fit for their own projects.

**Comment by Areloch** [comment]
Sounds good to me. I'll get an updated version of this PR hammered out tomorrow then.

**Comment by Areloch** [comment]
Submitted an updated PR with the suggested paramters: PR #1375 As such, I'll close this PR.

I would still like to thank Winterleaf for looking into updating these in the first place.

**Pull request closed without merging**
