### PR TITLE
OpenALEffects

### PR DESCRIPTION
**Pull request by marauder2k7**
Ground work, this commit enables reverb zones and opens the slots for
other effects to be added later. Tested using the full template. Build
your openal dll and your full.exe use one of the environment presets and
it will work

### CODE REVIEW

**Comment by marauder2k7** [comment]
i should add this also gives the option for exponential falloff

**Comment by Areloch** [comment]
Seems to all work, did note a typo with "PresetFroest" presumably that's supposed to be PresetForest?

Also, if you could correct the indentations on the SFXEnvironment definitions, and the typo, i think it's good to go :)

**Comment by marauder2k7** [comment]
yeah it was supposed to be preset forest lol sorry rushing to test it out was a bit excited.

**Review by Areloch — APPROVED** [review]

**Comment by wcb88** [comment]
bump
edit: works for me

**Pull request merged**
