### PR TITLE
Volumetric Fog with corrections

### PR DESCRIPTION
**Pull request by Areloch**
Based on the Winterleaf PR #1059, this adds corrections so that it works with HDR being active, and also utilizes ambient color so that it works with day/night cycles, rather than being unlit during low-light settings.

### CODE REVIEW

**Comment by eightyeight** [comment]
Nice!

**Comment by rextimmy** [comment]
A few of the shaders have text comments from the vehicle scripts. Example https://github.com/GarageGames/Torque3D/pull/1445/files#diff-d60227b88a44f1c0efc02bff45296431R23

**Comment by Areloch** [comment]
Yeah, it looks like there's just several chunks of this that are a bit weird. I'm working through the whole thing manually to try and shore up those weird bits that snuck past everyone the first go around.

**Comment by Areloch** [comment]
Redid this with #1478

**Pull request closed without merging**
