### PR TITLE
Include navigation and testing modules by default

### PR DESCRIPTION
**Pull request by eightyeight**
* They are both useful and can easily be turned off.
 * Navigation being off by default causes problems with the navmesh editor, which is _included_ by default, but nonfunctional unless the module is included.
 * Navigation can kind of be considered a stock feature.

The only problem is that I see no way to do something equivalent with the project generator. We could add `includeModule` to the Templates' default config files, but this won't show up in the manager UI when you create a new project.

### CODE REVIEW

**Comment by LuisAntonRebollo** [comment]
Fixed compilation on Linux.

**Comment by eightyeight** [comment]
T_T thanks for that, I meant to come back and check it but then bedtime happened. Also it appears there's no way to do this in the project manager. I think. I will try to make that happen.

**Comment by eightyeight** [comment]
Project manager 2.2 will allow setting default modules for inclusion, so I think this is good to go.

**Comment by eightyeight** [comment]
Current error:

    ../../../../Engine/source/platform/test/platformTimerTest.cpp:68:54: error: no matching function
    for call to ‘JournaledSignal<void(int)>::notify(TimeManager_BasicAPI_Test::TestBody()::handle*,
    void (TimeManager_BasicAPI_Test::TestBody()::handle::*)(S32))’
        time.timeEvent.notify(&handler, &handle::timeEvent);
                                                          ^

:sweat:

**Pull request merged**
