### PR TITLE
Multiple canvas support for GL and DX11

### PR DESCRIPTION
**Pull request by rextimmy**
Add support for multiple canvas for GL & DX11. Do note there is a problem with SDL and multiple windows but that is a separate case. All 3 gfx work perfectly with win32 platform code.

### CODE REVIEW

**Comment by JeffProgrammer** [comment]
@Areloch if you want this in 3.10 I can try to take a look at SDL.

**Comment by Areloch** [comment]
@JeffProgrammer If you would, that'd be pretty sweet. Can see about squeezing it in on the RC2 if possible.

**Comment by Areloch** [comment]
We'll want to do another PR to get it sorted for SDL, but this looks good on the windows-specific side atm, so this'll merge in.

**Comment by JeffProgrammer** [comment]
OK, i'll see if i can get to SDL before 3.10 release. if not sorry D:

**Pull request merged**
