### PR TITLE
Fixed some minor compiler warnings on Linux

### PR DESCRIPTION
**Pull request by raistlin**
I am building this project on linux, gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13), and I was shocked to get more than 20.000 compiler warnings. So I just started to clean some of them.

I plan to add more compiler warning clean commits if this little commits are accepted and merged.

### CODE REVIEW

**Comment by eightyeight** [comment]
This is definitely significant and something I want to deal with (see #1150). Just quickly, does the warning go away if you use `#if defined(_MSC_VER) && _MSC_VER > 1000`? Would be preferable to having nested `#if`s, but if not then I guess we'll go this way.

**Comment by raistlin** [comment]
Added some more fixes.

**Comment by eightyeight** [comment]
Looks great. I'll give this a quick test later but it should be good to go.

**Comment by eightyeight** [comment]
Thanks for the contribution!

**Pull request merged**
