### PR TITLE
Fix for fuzzy borders between textures

### PR DESCRIPTION
**Pull request by lukaspj**
A fix for the issue described by Richard at: https://github.com/GarageGames/Torque3D/pull/710#issuecomment-62199643

### CODE REVIEW

**Comment by Areloch** [comment]
Seems to work for me. I did the outpost mission and blended a the various terrain materials against each other and it seemed to smoothly blend from one to another.

**Comment by eightyeight** [comment]
We should probably manually merge this into `release-3.7` since the other terrain changes are in 3.7.

**Comment by eightyeight** [comment]
We should probably manually merge this into `release-3.7` since the other terrain changes are in 3.7.

**Comment by eightyeight** [comment]
Merged in 69f2efa.

**Pull request closed without merging**
