### PR TITLE
Hardware Skinning Support

### PR DESCRIPTION
**Pull request by jamesu**
- Supports GL, D3D9 & D3D11
- Extends vertex formats & shadergen to support blend indices and weights
- Adds basic support for using 4x3 matrices for shader constants
- Supports software fallback

### CODE REVIEW

**Comment by Lopuska** [comment]
Congratulations! Awesome job!

**Comment by jamesu** [comment]
Added the attribute fix from az with a slight mango twist.

**Comment by rextimmy** [comment]
Haha yeah i like the mango twist , looks nicer than my original way ;)

**Comment by Lopuska** [comment]
Seems to be fine for me :)
There are conflicts in this branch, @jamesu Please, can you resolve them?

**Comment by jamesu** [comment]
Rebased. Also added the fix for the pink water in D3D9.

**Pull request merged**
