### PR TITLE
Implementation of sRGB image support

### PR DESCRIPTION
**Pull request by Areloch**
Overhauls the linearization setup to utilize the sRGB image types, as well as refactors the use of ColorF and ColorI to be properly internally consistent. ColorIs are used only for front-facing/editing/UI settings, and ColorFs, now renamed to LinearColorF to reduce confusion of purpose, are used for color info in the engine itself. This avoids confusing and expensive conversions back and forth between types and avoids botches with linearity. Majority work done by @rextimmy

### CODE REVIEW

**Comment by John3** [comment]
I cleaned and recompiled succeful, for me my t3d crashed,  In the console.log it's end in here: 
```

DebugDrawer Enabled!
GFX Init:
   Null device found
   Direct 3D (version 11.x) device found
   OpenGL device found

GFXStringEnumTranslate: Unassigned value in GFXStringTextureFormat: 11
GFXStringEnumTranslate: Unassigned value in GFXStringTextureFormat: 24
GFXStringEnumTranslate: Unassigned value in GFXStringTextureFormat: 33
GFXStringEnumTranslate: Unassigned value in GFXStringTextureFormat: 34
GFXStringEnumTranslate: Unassigned value in GFXStringTextureFormat: 35
Console trace disabled.
C:/Users/John/Documents

--------- Parsing Arguments ---------
Attempting to create GFX device: NVIDIA GeForce GTX 260 (D3D11) []
```

**Comment by Areloch** [comment]
I don't see that issue on a clean build. Does it work if you try OGL?

I wonder if a 260 is old enough that it may not support, or fully support the sRGB format?

**Comment by John3** [comment]
hi areloch, yes I can run with opengl. Maybe is too old the graphics card...

**Comment by rextimmy** [comment]
Aah i see what has happened here, the d3d11 code has been merged with a different version of the d3d11 gfx device and thus doesn't have the required d3d feature level support in it, so yeah hence your crash. This PR will have to be fixed up and or redone.

**Comment by Areloch** [comment]
I don't have a graphics card that old on hand, so testing the solution is tricky, but I did roll back the feature level check code. I put it in a new branch to keep this one clean while we try and get the fix locked in. It's located [here](https://github.com/Areloch/Torque3D/tree/sRGB_Implementation_D3D10_FixTest) please test it out and lemme know if that fixed it for you or not.

**Comment by John3** [comment]
Build FAILED https://pastebin.com/qu54ayfU

```
1>  gfxD3D11Device.cpp
1>D:\Torque3D\dev\Engine\source\gfx\D3D11\gfxD3D11Device.cpp(527): error C2065: 'mVertexShaderTarget': undeclared identifier
1>D:\Torque3D\dev\Engine\source\gfx\D3D11\gfxD3D11Device.cpp(528): error C2065: 'mPixelShaderTarget': undeclared identifier
1>D:\Torque3D\dev\Engine\source\gfx\D3D11\gfxD3D11Device.cpp(530): error C2065: 'mShaderModel': undeclared identifier
1>D:\Torque3D\dev\Engine\source\gfx\D3D11\gfxD3D11Device.cpp(533): error C2065: 'mVertexShaderTarget': undeclared identifier
1>D:\Torque3D\dev\Engine\source\gfx\D3D11\gfxD3D11Device.cpp(534): error C2065: 'mPixelShaderTarget': undeclared identifier
1>D:\Torque3D\dev\Engine\source\gfx\D3D11\gfxD3D11Device.cpp(536): error C2065: 'mShaderModel': undeclared identifier
1>D:\Torque3D\dev\Engine\source\gfx\D3D11\gfxD3D11Device.cpp(539): error C2065: 'mVertexShaderTarget': undeclared identifier
1>D:\Torque3D\dev\Engine\source\gfx\D3D11\gfxD3D11Device.cpp(540): error C2065: 'mPixelShaderTarget': undeclared identifier
1>D:\Torque3D\dev\Engine\source\gfx\D3D11\gfxD3D11Device.cpp(542): error C2065: 'mShaderModel': undeclared identifier
2>------ Build started: Project: INSTALL, Configuration: Release x64 ------
2>  -- Install configuration: "Release"
```

**Comment by Areloch** [comment]
Looks like I'd derped when I was checking stuff in. Corrected that and added back in a few things that timmy spotted I'd missed. Also suggested a method for me to test 10 compatibility which seemed to work on my end, so go ahead and give that branch a whirl again.

**Comment by Azaezel** [comment]
Seems to work with the latest. @John3 , can you verify your end?

**Comment by John3** [comment]
yep, tonight will apply this three patches in the lasted build [8943c67](https://github.com/GarageGames/Torque3D/commit/8943c673fb876a50dc87d2ba862d31eb202ce6da), 
- [patch #2023](https://patch-diff.githubusercontent.com/raw/GarageGames/Torque3D/pull/2023.patch) 
- [patch eed89d](https://github.com/Areloch/Torque3D/commit/eed89deef6d0f5b8d0e2e38a06a43b6fea22bdbd.patch) 
- [path 36c2e](https://github.com/Areloch/Torque3D/commit/36c2e1958ed0fca12a53f46b31ed43d7effc0102.patch) 

will clean the tmp/cache and compile.

**Pull request merged**
