### PR TITLE
Added gui functionality for vehicle re-mapping as per #950

### PR DESCRIPTION
**Pull request by aaravamudan2014**
Added vehicle re-mapping functionality for the vehicle movements (forward, backward, brake).
Essentially just added a branched functionality if re-mapped functionality is vehicular without affecting the original functionality. Please let me know if there is anything to change.

### CODE REVIEW

**Comment by Areloch** [comment]
Hey dude, thanks for this!

Looks like there's a couple spots where the formatting, like indentation and brackets went a little squirrely.

If you can clean those spots up, I can finish testing this and see at getting it rolled in.

For reference in case you didn't know, here's our coding styles guidelines [here](http://wiki.torque3d.org/coder:code-style-guidelines)

**Comment by aaravamudan2014** [comment]
Hey, I fixed the style problems. The original file had some tabs instead of spaces, i fixed some of those too.  let me know if there is anything else to change.

**Comment by killsap** [comment]
Looks good to me.

**Comment by aaravamudan2014** [comment]
I squashed all commits into a single commit  591ddf6ae15e382d319c23c2c74f91866e041cf1

**Comment by killsap** [comment]
@Areloch , this looks good. If you don't mind, what is your testing procedure used here? I would like to make sure I am testing any fix I submit properly as well.

**Comment by Areloch** [comment]
@killsap Pretty straightforward, most of the time. Just take an up to date checkout of the main devhead repo, pull down the PR from the originating fork/branch, and then do a clean compile of the engine and/or install of the scripts where applicable.

Then just do a test of functionality to make sure it behaves as expected. Ideally you do both Debug and Release, but if you have to only pick one, pick Release. Debug has more safeties and catches if there are incorrect values, so if something is broken, Release is much more likely to let you know.

**Pull request merged**
