### PR TITLE
Linux

### PR DESCRIPTION
**Pull request by LuisAntonRebollo**
Linux implementation.

### CODE REVIEW

**Comment by eightyeight** [comment]
So which of these PRs is the right one? They all seem to add the SDL library.

**Comment by LuisAntonRebollo** [comment]
Look at [Add support for Linux / SteamOS](https://github.com/GarageGames/Torque3D/issues/588), are by merge order.

**Comment by eightyeight** [comment]
:+1:

**Comment by LuisAntonRebollo** [comment]
I need to update CI server for x64 builds :(

**Comment by LuisAntonRebollo** [comment]
Tested on Win8 x32/x64 and Ubuntu x64.

**Pull request merged**
