### PR TITLE
Fixes issue #1277

### PR DESCRIPTION
**Pull request by Areloch**
Adds the file path to the saveDataFile call (missionpath\missionname.forest as the format)

### CODE REVIEW

**Comment by eightyeight** [comment]
#1277. @aurodev does this fix things for you?

**Comment by Areloch** [comment]
Az spottd that I left in the hardcoded theForest name on the object, as well as inadvertently bypassing the datafile field in favor of purely the missionname.forest convention.

I'll make changes to this PR when I get home from work to rectify those

**Comment by eightyeight** [comment]
Heh I assumed those were how the editor worked.

**Comment by Areloch** [comment]
Technically, yes. But that's no reason to let related issues persist : P

I've updated the PR to correct those issues as well as a related bug with forest object creation I found when correcting the PR.

Feel free to give it a re-testing. For the moment I'll remove the final review tag.

**Comment by aurodev** [comment]
This eliminates the empty file save error but does not actually save forest data. Successfully saves a level with an empty forest but on adding trees does not actually save the level.  This is after adding a forest, saving empty, exiting, restart, adding tree, attempting to save level.

Pasted main.cs from the corrected path slash typo fix, just copied it raw
https://github.com/Areloch/Torque3D/blob/a032ec464133bfd1ee542437275d412677112253/Templates/Full/game/tools/forestEditor/main.cs

Tried with the latest git development and a zillion different combos  :)

I can get things like this to save forest data:
 theForest.saveDataFile("levels/theForestSaveHardcoded.forest");
or
theForest.saveDataFile(theForest.dataFile);


As far as I can tell the initial forest file is not being created by this line, it is created elsewhere (even when commenting this line)
 %forestObject.saveDataFile(%path @ "/" @ %missionName @ ".forest");


Is the forestObject valid here?
This code doesn't seem to be reached:
   //First, find out if we have an existing forest object
   %forestObject = parseMissionGroupForIds("Forest", "");
 
   if ( isObject( %forestObject ) )
   {
      //We do. Next, see if we have a file already by polling the datafield.
      if(%forestObject.dataFile !$= "")
      {
         //If we do, just save to the provided file.
         %forestObject.saveDataFile(%forestObject.dataFile);
      }
      else
      {
         //We don't, so we'll save in the same place as the mission file and give it the missionpath\missionName.forest 
         //naming convention.
         %path = filePath(%missionFile);
         %missionName = fileBase(%missionFile);
         %forestObject.saveDataFile(%path @ "/" @ %missionName @ ".forest");
      }
   }



Just want to say Torque rocks and thanks for all the hard work. :+1:

**Comment by aurodev** [comment]
Apologies if I have missed an update to this issue, I pulled down the dev branch, pasted the forest main.cs and tried that.

**Comment by aurodev** [comment]
Fixes the issue on my end. 
Creates initial forest, populates, saves level with forest, loads an existing forest data file, all ok as far as I can tell.

Thx!

Pulled down the zip from here:
https://github.com/Areloch/Torque3D/archive/e8f9c6775a385bd5cc2d8d68187fa43cec42b332.zip

**Pull request closed without merging**
