### PR TITLE
footstep and impact enum extension support

### PR DESCRIPTION
**Pull request by Azaezel**
Removes hardcoded case statements in favor of an offset-driven approach.

While the enums were kept for this for backwards compatibility, I'd strongly advise 4.0 shifts to a more script-driven vector+key approach vs the vector+enum+hardcoded script exposed names.

### CODE REVIEW

**Comment by Azaezel** [comment]
The editor doesn't really let you, but fair enough from a manual typo-possibility.

**Comment by Lopuska** [comment]
Cute changes (:

**Comment by dottools** [comment]
Makes a lot more sense this way.

**Comment by Lopuska** [comment]
Works, elegant, code more readable. A+ :P

**Pull request merged**
