### PR TITLE
OSX de-deprecation (profiler and macFileIO)

### PR DESCRIPTION
**Pull request by elfprince13**
Fixed a number of deprecated API usages on OS X, as well as made the move and copy operations share a bit more code, and both a bit safer.

### CODE REVIEW

**Comment by dottools** [comment]
Formatting problem with tabs vs spaces.

**Comment by elfprince13** [comment]
Is anyone aware of a simple setting to force Xcode to use the style conventions T3D on a per-project basis? Currently it auto-corrects spaces to tabs when I edit a line, which makes this a bit miserable to match up.

**Comment by elfprince13** [comment]
Okay - should be good here now with spaces.

**Comment by JeffProgrammer** [comment]
http://editorconfig.org/ @elfprince13

**Pull request merged**
