### PR TITLE
PhysX 3.4 support

### PR DESCRIPTION
**Pull request by rextimmy**
Attempt number 2.

PhysX 3.4 support, tested on windows 10, linux mint 18.1 and macOS sierra. Added a new console variable called $Physics::gpuAccelerationAllowed (disabled by default). When enabled physx will attempt to create a cuda context and if successful will enable Gpu Rigid Body(GRB) support.  If no supported nvidia hardware is found, a simple warning will be put in the log and it will than resort back to using the cpu dispatcher for everything.

GRB support is only available on windows and linux.

### CODE REVIEW

**Comment by Lopuska** [comment]
Really cool stuff!
Sorry @Areloch, I accidentally added you as reviewer

**Comment by Areloch** [comment]
@Lopuska Haha, no worries dude :)

@rextimmy Most excellent, good sir!

**Comment by OTHGMars** [comment]
I tested this PR with Windows 8.1, PhysX sdk 3.4.1 and vs2015 x64. The physX build did not create the PhysX3Gpu .lib files so the game would not build without removing them from linker input. The corresponding .dll files are present in the ./bin directory and did get copied by the install projects. I don't see source for that library in the physx 3.4 repo. The game compiled and ran with them removed. This commit updates the cmake for windows. https://github.com/OTHGMars/Torque3D/commit/55bba16fc4ef0528d5d4daa9123f6a394a5c5d85
I do not have the ability to test on linux or mac.
Very nice work on the update to 3.4.

**Comment by rextimmy** [comment]
Aah ok no worries @OTHGMars , they must have changed something in the 3.4.1 release, i only tested it against the original 3.4.0 release. I'll take a look over it when i get a chance and see what is different now.

**Pull request closed without merging**
