### PR TITLE
JSON support

### PR DESCRIPTION
**Pull request by MusicMonkey5555**
Added a JSON class that is open to script  and inherits from the array object. It is basically the same as the array object only with some added functions/variables to handle the type handling and writing out to a string.

There is no reading in, perhaps that can be added by someone else or in the future.

### CODE REVIEW

**Comment by Lopuska** [comment]
That's really useful for multiplayer and network related gameplay like leaderboard and social media integration that expose a json api.
I'll take a look this soon! 
Thank you for contribution.

**Comment by dottools** [comment]
Pretty sure TAML already has JSON support. Could just use that instead.

**Comment by Lopuska** [comment]
@dottools Well, I'm gonna to check this. If that's the case, It's better to avoid this PR for redundant feature and more useless code to maintain.
Thanks for that hint.

**Comment by Lopuska** [comment]
https://github.com/GarageGames/Torque3D/tree/development/Engine/source/persistence/rapidjson
https://github.com/GarageGames/Torque3D/tree/development/Engine/source/persistence/taml/json

I close this as redundant feature. No reason to have duplicate json parser class.
Probably @MusicMonkey5555 implemented this when TAML was still not present in T3D.
TAML commits have been pushed to repo 4 months ago as this PR is much older.
Thanks @dottools for your good eye :P

Anyway, thank you very much @MusicMonkey5555 to share your great work with us.
Next days i'm going to see your other pending PRs.

**Pull request closed without merging**
