### PR TITLE
Exiting typo fix

### PR DESCRIPTION
**Pull request by elfprince13**
Fixed a typo, plus lots of white-space fixes.

### CODE REVIEW

**Comment by Areloch** [comment]
are the 

ConnectionNotifyEvent*   smConnectionNotify = NULL;
ConnectionAcceptedEvent* smConnectionAccept = NULL;
ConnectionReceiveEvent*  smConnectionReceive = NULL;
PacketReceiveEvent*      smPacketReceive = NULL;

Declarations supposed to have the Net namespace on them, then? I remember we had to do a quick rollback before. I'm not getting any compilation errors or anything, just wanted to check if we were sticking with them being inside the Net namespace, or keeping them global.

Other than that, this PR's looking good.

**Comment by elfprince13** [comment]
They're static members of the Net struct declaration - hence the naming convention of `sm` rather than `g`.

**Comment by Areloch** [comment]
Ok, so the way it is in this PR should be considered correct then. Just wanted to be sure because like said, we'd had to run that quick rollback from before.

**Comment by elfprince13** [comment]
Yeah, this PR should be the correct version.

~Thomas

**Pull request merged**
