### PR TITLE
Natural (without 2-km limitations) heights of terrain.

### PR DESCRIPTION
**Pull request by syrokomskyi**
See http://garagegames.com/community/forums/viewthread/136055 for details.

Demo [level](https://drive.google.com/file/d/0B4G7HDT9STV-ekpiS2hyQUE5LTQ/edit?usp=sharing) and [video](http://youtube.com/watch?v=Kkgmsz7416w).

torque3d-mountain-everest

### CODE REVIEW

**Comment by dragutux** [comment]
hmmm apparently, it might be me being right a year ago about signmotion pr that comes to bite my ass because i havent changed to u32 yet
fuck you past me :D

oh yeah the issue as it is : colisions completely gone wrong on bullet with this.

**Comment by HeadClot** [comment]
So just curious here - 
Does this affect just height of terrains or both height and size of terrains? Either way this is great to see.

@dragutux - You might be encountering floating point precision issues not sure though.

**Comment by eightyeight** [comment]
@HeadClot this was not merged, it was discarded due to containing C++11 code (and because we weren't sure if we wanted it :P).

**Comment by dragutux** [comment]
@HeadClot nah floating points can  handle 85 km's, its a shape problem i'm encountering, this affect only the height of terrain to answer you basically with this your heightscale isnt 256 by default but more like a real number like 2 or refined to 2.56 for example, else you do get spiky terrain ;)

**Comment by dragutux** [comment]
btw i'm working on a solution, watch my greed06 branch commits

**Comment by HeadClot** [comment]
@eightyeight - Ah ok, sad to see it was not committed in the main branch of torque 3D. I am reading that you guys support VS2008 at the moment. Do you guys support VS2013 yet? I know VS 2013 community came out recently and is awesome for compiling cross platform stuff.

@dragutux - Awesome and good to know. Will keep an eye on it :)

**Comment by eightyeight** [comment]
VS2013 support has been in for some time. VS2008 was supported until recently when we accidentally broke it. I'm going to try to make sure we still support it for 3.7, but we'll most likely break compatibility soon.

**Pull request closed without merging**
