### PR TITLE
Added invalid text visual feedback

### PR DESCRIPTION
**Pull request by MusicMonkey5555**
Now instead of just having a sound when you enter bad text there is some visual feedback as well.

### CODE REVIEW

**Comment by dottools** [comment]
Conflicts with a disabled control state of which is what ColorNA is used for. Of which NA means Not Available. Which on normal Window UI is the 'grayed out' state control color.

**Comment by eightyeight** [comment]
It's a good idea, but as @dottools says there should be a separate colour for this state.

**Comment by MusicMonkey5555** [comment]
I think I just used that because it wasn't being used in any rendering for that control. I can added it to the guiTypes though and commit that. Suppose it may be a nice feature to add to other controls if need be in the future.

**Comment by Lopuska** [comment]
Thank you! I'm going to review this soon! I close this PR as a duplicate of all-in-one PR: #1334

**Pull request closed without merging**
