### PR TITLE
Fix issue 396

### PR DESCRIPTION
**Pull request by JeffProgrammer**
This fixes issue #396 

The regex expression assumed that the programmer would type a character after the beginning of the summary comment line. This now stops it from requiring an extra char.

This will now compile:
```
///
function pq()
{
}
```

### CODE REVIEW

**Comment by eightyeight** [comment]
I believe the meaning is slightly different now. Previously `////` was not parsed ad a doc block, because the grammar specified `[^/]` immediately after `"///"`. Now the not-slash is optional, and in the case of four slashes, the fourth slash will be parsed as part of the `[^\n\r]` block.

Reflecting, I think the solution should actually be `("///"([^/][^\n\r]*)?[\n\r]*)+`. Will that work?

**Comment by JeffProgrammer** [comment]
someone slap me to do this, keep forgetting.

**Comment by eightyeight** [comment]
:hand:

**Comment by JeffProgrammer** [comment]
should be fixed now. Can someone confirm?

**Comment by eightyeight** [comment]
Lol CI is totally broken. Hurrah. Works for me in linux.

**Comment by JeffProgrammer** [comment]
glad to hear its working good on linux too ;)

**Comment by eightyeight** [comment]
Shoot. Apparently it doesn't actually fix the issue on Windows. Wat.

**Comment by eightyeight** [comment]
[This](https://github.com/eightyeight/Torque3D/commit/2c6cced0cf97f057a2aa3a8e2352efb96c47f0df) was the best I could do.

**Comment by JeffProgrammer** [comment]
my fix compiles scripts bytecode fine though on windows, What do you mean?

**Comment by eightyeight** [comment]
Did you test all scripts? With `\r\n` replaced by `\n`? For me, your fix didn't work on `audio.cs` with newlines replaced. I actually found a way to keep current behaviour w.r.t `////`. See #1220.

**Pull request closed without merging**
