### PR TITLE
standardization, and fix for editors with non-occulous builds (missing popups)

### PR DESCRIPTION
**Pull request by Azaezel**
\game\tools\worldEditor\scripts\editor.ed.cs function Editor::create() sets $GameCanvas = Canvas; with the rest following conversion conventions for https://github.com/GarageGames/Torque3D/pull/1297 . (see https://github.com/GarageGames/Torque3D/pull/1297/files#diff-e50af352c48fb4969d220ecd5a7521b9L79 on down)

 :

### CODE REVIEW

**Comment by eightyeight** [comment]
How can I reproduce the problem? I tested a couple of editor popups and they appear to work.

**Comment by Azaezel** [comment]
At the time, the repro-check was adding and removing a terrain, and not receiving a popup. Must have been a transcription error this end somehow.

**Comment by eightyeight** [comment]
I'll double check. So you think these changes are unnecessary? Or going to resubmit?

**Comment by Azaezel** [comment]
Willing to say redundant unless similar lack of popups are otherwise reported, but will keep the fork around for say, a week or so just in case.

**Comment by eightyeight** [comment]
Okie dokie, thanks for this.

**Pull request closed without merging**
