### PR TITLE
Walkabout navigation editor

### LINKED ISSUE #956: Navmesh saving doesn't use filesystem abstraction
Instead it just calls C++ file IO functions directly. Bad Daniel. Specifically, [here](https://github.com/GarageGames/Torque3D/blob/development/Engine/source/navigation/navMesh.cpp#L817) and [here](https://github.com/GarageGames/Torque3D/blob/development/Engine/source/navigation/navMesh.cpp#L891).

### PR DESCRIPTION
**Pull request by eightyeight**
For #1052. Includes the first half of that issue and fixes #956. I can break this up if people would prefer. Particularly the changes to AIPlayer may need more careful review in terms of code style (use of defines everywhere).

### CODE REVIEW

**Comment by dottools** [comment]
Sweet

**Comment by TheDushan** [comment]
some files are missing in this pull

Missing file: tools/navEditor/NavEditorGui.cs!
Missing file: tools/navEditor/NavEditorAboutDlg.gui!
Executing tools/navEditor/NavEditorConsoleDlg.gui.

After executing NavEditorConsoleDlg.gui I get (simobject.cpp(1533) : Warning - SimObject::linkNamespaces -- Namespace linkage already in place)

**Comment by eightyeight** [comment]
Whoops, those were removed intentionally but I guess I forgot to remove the `exec`s. Thanks, I'll check on that namespace error.

**Comment by Azaezel** [comment]
using that https://github.com/Azaezel/Torque3D/tree/linkNamespacesDebugOutput bit:

SimObject::linkNamespaces -- Namespace linkage already in place NavEditorConsoleListener

**Pull request merged**
