### PR TITLE
Fix Linux rpath.

### PR DESCRIPTION
**Pull request by LuisAntonRebollo**
Necesary for distribute binaries.

### CODE REVIEW

**Comment by eightyeight** [comment]
@bpay (I think it was) advised that `rpath` should be set to `$ORIGIN`, not `.` for security reasons. I'm not fully aware of the differences, though.

**Comment by LuisAntonRebollo** [comment]
Changed.

I have curiosity about diference. Anyone can post some link with info? Plz :P

**Comment by bpay** [comment]
see discussion on #1158

**Comment by LuisAntonRebollo** [comment]
wow... i miss some important talk :P

Thx a lot.

**Comment by eightyeight** [comment]
Thanks Ben. Yeah it failed when I tried it as well. For now, maybe we should rely on documentation, or run scripts that provide the correct path at runtime. Can anyone verify that IDEs aren't doing something about this when you build with them? I've only built from the command-line. AFAIR Terminal Overload is providing users with a script they run instead of the executable directly. @fr1tz could comment.

**Comment by fr1tz** [comment]
I assume using "." instead of "$origin" causes the linker to search for the libs relative to the current working dir. If that's the case it would be a potential security risk (a bit like having "." in your PATH).
For Terminal Overload releases I use '$ORIGIN/lib' as rpath (set using the "chrpath" utility). The script @eightyeight mentioned just checks if a 32-bit version of libGL is available, because that's the only dependency not included in the release distribution (which even includes a 32-bit version of Linux' dynamic linker). The script is located at https://github.com/fr1tz/terminal-overload/blob/master/My%20Projects/main/game/overload.sh and it seems to work. Or at least there's a lack of feedback that it doesn't work ;)

**Comment by LuisAntonRebollo** [comment]
Fixed Clang.

**Pull request merged**
