### PR TITLE
Simplify readme

### PR DESCRIPTION
**Pull request by eightyeight**
[Rendered version.](https://github.com/eightyeight/Torque3D/blob/simplify-readme/README.md) For #882. Port to the new wiki is now complete, and this readme removes all outdated links. It also removes a lot of duplicate information that is now on the wiki.

### CODE REVIEW

**Comment by JeffProgrammer** [comment]
it's forums.torque3d.org. your link is wrong ;)

**Comment by eightyeight** [comment]
Wow, how did I do that :sweat_smile:

**Comment by JeffProgrammer** [comment]
:+1:

**Comment by LuisAntonRebollo** [comment]
More simple and removed outdated info, i like :)

**Pull request merged**
