### PR TITLE
corrects getrandom to behave as documented.

### PR DESCRIPTION
**Pull request by Azaezel**

### CODE REVIEW

**Comment by eightyeight** [comment]
Bug was introduced in #1072, so this will be merged into `release-3.7` manually.

**Comment by Duion** [comment]
Better hacked than broken.

**Comment by eightyeight** [comment]
:+1:

**Comment by Duion** [comment]
merge it, merge it, merge it

**Comment by eightyeight** [comment]
That counts as community feedback :stuck_out_tongue_closed_eyes:. Merged in f8d41a2b96!

**Pull request closed without merging**
