### PR TITLE
[WIP] Update the C-Interface

### PR DESCRIPTION
**Pull request by lukaspj**
This PR includes mainly 4 things:

* A clean-up of some existing console functions, with incorrect information in ConsoleDoc and incorrect types
* Update the ConsoleDoc dump, to provide some more information
* Fix existing C-Interface, and cleanup some inconsistencies
* Add some more C-Interface functionality, like hooks from engine to interface.

(This has nothing to do with C#, this is a general fix and improvement of existing Torque3D functionality)

### CODE REVIEW

**Comment by dottools** [comment]
Nicely done. However you're not following the [coding style guidelines](http://wiki.torque3d.org/coder:code-style-guidelines) for [`{` braces and single-line `if()` statements](http://wiki.torque3d.org/coder:code-style-guidelines#toc6).

**Comment by lukaspj** [comment]
Dammit, well it's still WIP! I will update to follow guidelines :P

**Comment by Areloch** [comment]
Pretty sure this has been made completely redundant by #2136 aye?

**Comment by lukaspj** [comment]
I had no recollection of this PR. Yeah, pretty sure this is just my older attempt. I will have a look through, to see if there is anything that should be brought over to the new one.

**Pull request closed without merging**
