### PR TITLE
Fix for rendering particles to the glow buffer

### PR DESCRIPTION
**Pull request by lukaspj**
Fix for #1315

### CODE REVIEW

**Comment by lukaspj** [comment]
Btw fun fact, the only occasion it would work earlier, was when the rendering order was such that it would render to the glow buffer exactly after rendering the particles :P Pure coincidence we didn't spot it right away :P

**Comment by Azaezel** [comment]
works

**Comment by eightyeight** [comment]
I'm wary of exposing methods that are evidently intended to be private. Can `RenderGlowMgr` be a friend of `RenderParticleMgr` so that we can at least contain the leak? Or is there a proper way to communicate the information?

**Comment by lukaspj** [comment]
Meh, I'd say it doesn't make sense for those getter methods to be private anyways. But yeah we can make it a friend class.

**Comment by eightyeight** [comment]
If they should be part of the public interface, can we make a ticket to make them properly public in the future? I.e. drop the underscore, and maybe move them to an already-public section?

**Comment by Areloch** [comment]
Yeah, I think we can just do a cleanup pass on it in 3.8 or 3.9.

As for this, it looks good. If you didn't spot any problems Dan, I think we can roll this one in.

**Comment by eightyeight** [comment]
Sure thing. Do the honours if you like, but you'll need to cherrypick it onto `release-3.7` since the PR is targeted at development.

**Comment by eightyeight** [comment]
Cherry-picked in c5dd723.

**Comment by eightyeight** [comment]
Cherry-picked in c5dd723.

**Pull request closed without merging**
