### PR TITLE
Functions to get EXE Info

### PR DESCRIPTION
**Pull request by MusicMonkey5555**
Added console functions to get info from an executable like version
info, timestamp and more using a library.

### CODE REVIEW

**Comment by dottools** [comment]
Not sure why this belongs in a game engine and especially since this is Windows only specific. Only Windows executable and dynamic library files can have version info to query while all other platforms do not. This kind of code belongs in a platform specific tool outside of the engine.

**Comment by MusicMonkey5555** [comment]
Makes sense, I sometimes forget about cross platform. The reason we personally use it is to show version numbers and other information inside the game so the user knows what version they have. But I can understand why it would not belong in the head build.

**Comment by Azaezel** [comment]
if that's the inent, may try hooking into https://github.com/GarageGames/Torque3D/blob/development/Templates/Full/source/torqueConfig.h#L37-L43

**Comment by eightyeight** [comment]
https://github.com/GarageGames/Torque3D/blob/development/Engine/source/app/version.h

**Comment by Areloch** [comment]
So, should this just be closed since it'd make more sense to access either the torqueConfig or the version.h as per az and dan's suggestions?

I definitely think there should be script hooks, but probably using one of the above methods instead to keep things playing nice regardless of platform ;)

**Comment by Lopuska** [comment]
Closing this as we prefer wait a more portable/cross-platform solution.
Thank you very much @MusicMonkey5555 as always for your awesome contributions!

**Pull request closed without merging**
