### PR TITLE
Fix TinyXML Build errors

### PR DESCRIPTION
**Pull request by Ragora**
A new pull request for the one I had accidentally closed previously.

### CODE REVIEW

**Comment by eightyeight** [comment]
See #1471. This looks good.

**Comment by Areloch** [comment]
Hey Ragora, the change to the tinyxml.h path looks good, but was there a particular reason for removing the (*WriteCustomTamlSchema) declaration on line 438?

(Also, that's a lot of whitespace changes, haha).

**Comment by Ragora** [comment]
It was a redeclaration. Somewhere else in the same class there was already a definition which was also causing a build failure.

**Comment by Areloch** [comment]
Ah, dang. Good catch on that duplicate.

**Pull request merged**
