### PR TITLE
fills in profiler timer fallback

### PR DESCRIPTION
**Pull request by Azaezel**
as per remmed out lines in other samples. see https://github.com/GarageGames/Torque3D/issues/1349 for report, and https://gist.github.com/Azaezel/2aafb88cf0d642418051 for result

### CODE REVIEW

**Comment by eightyeight** [comment]
It's not exactly high-resolution bit it's better than nothing! Though, I wonder if we should look at [this C++11 solution](http://stackoverflow.com/a/21856299/945863). Oh, but of _course_ VS2012 doesn't implement it correctly. [Workaround.](http://stackoverflow.com/a/16299576/945863)

**Comment by JeffProgrammer** [comment]
Why not just use each platform's specific high performance counter? Windows: QueryPerformanceCounter/Frequency, Linux/unix: clock_gettime time.h, OSX: mach timer

That way it stays with the C++03 standard.

**Comment by dottools** [comment]
`std::chrono::high_resolution_clock` is really bad and should not be used. For one you don't know if it's really an alias to just `std::chrono::system_clock`, `std::chrono::steady_clock`, or something else as explained on [CPP Reference](http://en.cppreference.com/w/cpp/chrono/high_resolution_clock). Second neither of the first two clock sources are suitable for benchmarking/profiling code. You want a timer source that only increments on thread CPU usage, which there is not option to choose from in C++11.

Similar to what Jeff H. has said. We should be implementing platform specific timers that are known to be correct or good enough timer sources for profiling.
* For Linux (and Android) that's `clock_gettime(CLOCK_THREAD_CPUTIME_ID, &ts)`, [example](http://www.guyrutenberg.com/2007/09/22/profiling-code-using-clock_gettime/).
* For Windows that's `GetThreadTimes` and combining lpKernelTime and lpUserTime values: [GetThreadTimes() documentation](https://msdn.microsoft.com/en-us/library/ms683237%28VS.85%29.aspx).
* No idea about Mac OS X.

**Comment by eightyeight** [comment]
Roger that @dottools, thanks for the info. @Azaezel I'm going to merge this for now until we can work on a longer-term solution. I'm happy to take that on, unless you need it today ;).

**Pull request merged**
