### PR TITLE
readme update

### PR DESCRIPTION
**Pull request by John3**
badges =)

### CODE REVIEW

**Comment by John3** [comment]
Just in case anyone want to see how its look. (The LICENSE.md need to exist to load correctly the badge)

image

**Comment by Areloch** [comment]
Looks pretty sweet, only thing I'd say is the link to the main repo in the related repositories area is probably redudant ;)

Otherwise this looks nice. If you want to clip out that redundant link, this seems like it'd be good to go!

**Comment by rextimmy** [comment]
Yeah it does look better, i think the copyright year should read 2012-2016 though, not changed from 2012 to 2016 though

**Comment by John3** [comment]
Ok, changed.

Oh btw in the top, is added the license.

imagen

**Comment by JeffProgrammer** [comment]
yeah it's a new github feature they added that looks for the LICENSE file. pretty nifty eh :)

**Comment by Areloch** [comment]
Very cool! Thanks for the fixups :)

**Pull request merged**
