### PR TITLE
Win32 fullscreen fix partial

### PR DESCRIPTION
**Pull request by RoundedIcon**
A lot of resolutions look like this in fullscreen mode. http://i.imgur.com/DZozand.png
This fixes a few of them.

### CODE REVIEW

**Comment by RoundedIcon** [comment]
I did not notice this issue on a different pc when using a nvidia card or intel integrated graphics. This might be an issue with amd graphics cards only.

**Comment by RoundedIcon** [comment]
More testing - turning on gpu scaling in Radeon settings fixes / hides the issue. This pull request hides the issue for some resolutions when that is not on.

**Comment by dottools** [comment]
I see no problem with these changes provided no negative side effects.

**Comment by RoundedIcon** [comment]
To clear something up - The existence of the black bars is not the issue. The problem is that they appear on resolutions with aspect ratios that match the monitor. This isn't meant to be a final fix, it just makes the deeper engine problem of inconsistent bar behavior slightly less problematic.

**Comment by Lopuska** [comment]
In which render backends is present this issue? Because the query/enumeration of display modes differs between ogl and d3d.
See GFXGLDevice::enumerateVideoModes() and GFXPCD3D9Device::enumerateVideoModes()

And also new resolution change is handled differently.
in opengl we use ChangeDisplaySettings api and in directx a direct call to swapchain:
swapchain->SetFullscreenState()

I'll take a look in deeper way soon! (:

**Comment by RoundedIcon** [comment]
The problem happens with both d3d and ogl. Ogl has an additional problem as well - Increasing the resolution in full screen mode only changes the screen res. The game window starts shrinking into the upper left corner with large res increases.

**Comment by Lopuska** [comment]
I'm taking a look about this now. Thanks. Also this fix a different problem relative to fullscreen:
#1512

**Comment by Lopuska** [comment]
I close this as this is not fixing the issue. Also the problem should be fixed in a different way.
Please, open an issue ticket for taking trace of this! I'll try to investigate it after other priorities.
Thank you for your contribution. (:

**Pull request closed without merging**
