### PR TITLE
Forest wind emitter

### PR DESCRIPTION
**Pull request by eightyeight**
Redo of #896 with cleanup.

### CODE REVIEW

**Comment by Areloch** [comment]
Works fine for me.

**Comment by eightyeight** [comment]
What does the effect actually look like? I haven't see it in action, just refactored Vince's code. How can you see the sphere if it intersects the camera location?

**Comment by Areloch** [comment]
It pretty much forces it to render as much as it can. You still see some clipping  - I think due to issues with the near plane - but you can at least tell the circle still there and didn't inexplicably stop existing.

There's probably an even better way to do it for the future, but this should work well enough as a fix for the current method.

**Comment by eightyeight** [comment]
Double-sided sphere?

**Pull request merged**
