### PR TITLE
A couple of bugs and DarkUI as a template.

### PR DESCRIPTION
**Pull request by antonyjones67**
I can't figure out how to break up into multiple pull requests.

### CODE REVIEW

**Comment by dottools** [comment]
Uhhh.. Bug fixes and new features should be in separate usable PRs, not lumped into together. Makes it difficult to figure out what you've changed.

**Comment by antonyjones67** [comment]
On 1/12/2015 6:53 PM, Nathan Martin wrote:
>
> Uhhh.. Bug fixes and new features should be in separate usable PRs, 
> not lumped into together. Makes it difficult to figure out what you've 
> changed.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/GarageGames/Torque3D/pull/1104#issuecomment-69682715>.
>
>
Yup. Wasn't having any luck with that. Git Hub is not my friend. :(

**Comment by eightyeight** [comment]
Check out [this](http://torque3d.org/contribute/#pull-request-guide) and [this](https://github.com/GarageGames/Torque3D/wiki/How-To:--Submit-A-Pull-Request).

**Comment by antonyjones67** [comment]
thank you daniel!
i'll do better next time.

**Pull request closed without merging**
