### PR TITLE
Add support for abstract ConObjects

### PR DESCRIPTION
**Pull request by lukaspj**
Now abstract classes can be properly implemented in a way that makes them work with the editors (I know I'm rambling... Tired.. Ask for a better explanation if necessary :P )

Seeks to solve #1205

### CODE REVIEW

**Comment by lukaspj** [comment]
Okay so I'm a little clearer in my head now..

So this really seeked to solve an issue that came up with the ParticleSystemRefactor. 

If you have a structure like this:

* GameBase
  * AbstractClass
    * ConcreteClass

Then the editor will think that GameBase is the immediate parent, and not the AbstractClass. This seeks to fix that.

**Comment by eightyeight** [comment]
Are these script-only namespace/classes? Or actual C++ inheritance? Also when does the editor care about the inheritance hierarchy? The inspector?

**Comment by Azaezel** [comment]
datablock editor dropdowns and the like. Noticed when taking a first-pass review on the particle system refactor, that some conditions could trigger invalid lists. This'll fix that.

**Comment by lukaspj** [comment]
@eightyeight 

Aww :(
First

Yaay!
Second

First one is without this PR, second is with.

**Comment by Lopuska** [comment]
Closing it for conflicts issues New PR: #1535

**Pull request closed without merging**
