### PR TITLE
warning C4706: assignment within conditional expression

### PR DESCRIPTION
**Pull request by Azaezel**

### CODE REVIEW

**Comment by eightyeight** [comment]
I'd prefer `GameBase *gb = gc ? gc->get...() : NULL;` to avoid more of #1351. But good idea getting it out of the conditional

**Comment by Azaezel** [comment]
so
       GameBase *gb = gc ? gc->getCameraObject() : NULL;
      if (gb)
?

**Comment by eightyeight** [comment]
You got it. Thoughts?

**Comment by Areloch** [comment]
Yeah, I like that better as well.

**Comment by eightyeight** [comment]
:+1:

**Pull request merged**
