### PR TITLE
More x64 fixes

### PR DESCRIPTION
**Pull request by LuisAntonRebollo**
See  Issues on x64 builds #1144

### CODE REVIEW

**Comment by bpay** [comment]
These type aliases look a lot like macros. Can they be lowercased? I know the rest of the numeric typedefs are not, but I think it's too late to fix those...plus, they have numbers embedded (S32, F32) in them which makes them a little less macro-like.

**Comment by eightyeight** [comment]
Typedefs are type-level macros ;).

**Comment by LuisAntonRebollo** [comment]
I only added SPTR and UPTR types, becouse some ppl commented to me that c++ types dont look consistent with T3D types.

I prefer to use c++ style types, but we cant change old types. 

I'm going to separate fix and rename to diferent PRs.

**Comment by LuisAntonRebollo** [comment]
Continue discussion on #1162

**Pull request closed without merging**
