### PR TITLE
Update the repository for T3D documentation, the old is dead.

### PR DESCRIPTION
**Pull request by John3**
Maybe we can use @RichardRanft repository.

### CODE REVIEW

**Comment by RichardRanft** [comment]
Before you do, let me push my changes.  I'll try to remember it this week.

**Comment by John3** [comment]
thanks! @RichardRanft udated PR

**Comment by Areloch** [comment]
Yeah, just let us know when you're ready Rich and we can get this bumped.

**Comment by RichardRanft** [comment]
Technically RTS Part 1 is ready - Part 2 is about 35%, hopefully I'll get it in by the end of July.  The AI Tutorial will be a bit later - haven't started my rewrite yet.

**Comment by John3** [comment]
if RTS part 1 is ready, It can be pushed, right? because is the replace of the old RTS tutorial. Or we need ready Part 2 and Part 3?

**Comment by RichardRanft** [comment]
Part 1 replaces the old RTS Tutorial (well, not really "replaces" - it is the updated version).  Part 2 and 3 will extend it.

**Pull request closed without merging**
